dataviz-toolbox.html:
    title: Data Visualisation Toolbox
    data: dataviz-toolbox.yml
    template: lists.mustache  

ddj-toolbox.html:
    title: Data Journalism Toolbox
    data: ddj-toolbox.yml
    template: lists.mustache    

hosting.html:
    title: Hosting Options
    data: hosting.yml
    template: lists.mustache     

egypt-datasets.html:
    title: Egypt Datasets
    data: egypt-datasets.yml
    template: lists.mustache    

egypt-vcs.html:
    title: Egypt Venture Capitals
    data: egypt-vcs.yml
    template: lists.mustache 

egypt-orgs.html:
    title: Egypt Organizations
    data: egypt-orgs.yml
    template: lists.mustache  

egypt-hacks.html:
    title: Egypt Civic Hacking
    data: egypt-hacks.yml
    template: lists.mustache       
